name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

        # Verify test files have not been modified
      - name: Verify test files
        run: |
          # Generate hashes of the current test files
          find tests/ -type f -exec sha256sum {} \; > current_hashes.txt
          cat current_hashes.txt

          # Compare with the expected hashes
          if ! diff -q tests_hashes.txt current_hashes.txt; then
            echo "Error: Test files have been modified!"
            exit 1
          fi

      # Install dependencies (e.g., Check testing framework)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y check

      # Run `make test` to compile and run tests
      - name: Run tests
        run: |
          make test
